trigger:
 branches:
  include:
    - master

pr: none

pool:
  vmImage: 'Ubuntu-20.04'

jobs:
  - job: Build
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js 16'

      - script: |
         npm install
         npm run test
         npm run build
        displayName: 'Build'

      - task: ArchiveFiles@2
        displayName: 'Archive Files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
      - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        displayName: 'Publish Zip'
        artifact: drop

  - deployment: VMDeploy
    displayName: Production
    dependsOn: Build
    pool:
      vmImage: 'Ubuntu-20.04'
    environment:
      name: Linux
      resourceType: VirtualMachine
      tags: web
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
               cd ~/azagent/_work/1/drop
               rm -rf *
              displayName: 'Delete Files'
            - download: current
              artifact: drop
            - script: |
               cd ~/escapebot
               rm -rf dist node_modules
               cd ~/azagent/_work/1/drop
               unzip *.zip
               mv s/dist ~/escapebot
               mv s/node_modules ~/escapebot
               cd ~/escapebot
               pm2 delete escape
               pm2 start dist/src/index.js --name escape
              displayName: 'Start Application'