name: Sentry

on:
  push:
    branches: [ master ]

jobs:
  sentry_bot:
    name: Create Sentry Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: NPM Install
        run: npm i

      - name: Build
        run: npm run build

      - name: Get Version
        run: |
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          echo "VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        with:
          sourcemaps: './dist'
          environment: production
          version: ${{ env.VERSION }}
